include: package:lints/recommended.yaml

analyzer:
  exclude:
    - example/**
    - build/**
    - android/**
    - ios/**
    - web/**
    - windows/**
    - macos/**
    - linux/**

  language:
    strict-raw-types: true

  errors:
    todo: ignore
    missing_required_param: warning
    missing_return: warning
